### ISSUE TITLE
Should we rename the package?

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/dask_labextension-feedstock#1]
@conda-forge/dask_labextension the package name is `dask-labextension` and not `dask_labextension`, dash vs underscore, and that brings confusion when people try to port install instructions from PyPI to conda. Are you OK renaming the package?

**Comment by jakirkham** [comment]
This is a good question and had wondered the same myself when this went in.

Given the package [names itself dask_labextension in `setup.py`]( https://github.com/dask/dask-labextension/blob/v0.3.1/setup.py#L22 ), the conda-forge package name is consistent in that regard. Also running [`pip install dask_labextension` (as noted in the docs)]( https://github.com/dask/dask-labextension#installation ) works correctly. Admittedly the name on PyPI has a `-`, but this may be the typical story of converting `_` to `-` with Python package names.

It would be good to get @ian-r-rose's thoughts on this as well.

**Comment by ian-r-rose** [comment]
I'd be fine with renaming. I'd even like to rename in the package `setup.py`, if I felt confident that wasn't a breaking change. Unfortunately, I find the PyPI `-` vs `_` rules/normalization to be somewhat inscrutable and underdocumented.

**Comment by jakirkham** [comment]
> I'd be fine with renaming.

Great! This might be the easiest path forward.

> I'd even like to rename in the package `setup.py`, if I felt confident that wasn't a breaking change.

What if that was accompanied with a minor version bump?

> Unfortunately, I find the PyPI `-` vs `_` rules/normalization to be somewhat inscrutable and underdocumented.

Completely agreed. Have been able to [publish packages with an `_` in the past]( https://pypi.org/project/rank_filter/ ). Not sure why that doesn't work in all cases or generally why it matters at all.

**Comment by jakirkham** [comment]
Also it looks like you need 0.3.1 @ocefpaf. Is that correct? If so, what is driving the need for that version (given it is a few patch releases behind the current one)?

**Comment by ocefpaf** [comment]
> I'd be fine with renaming.

Done in #3 (@xhochy also approved #2.)

> I'd even like to rename in the package `setup.py`, if I felt confident that wasn't a breaking change. Unfortunately, I find the PyPI `-` vs `_` rules/normalization to be somewhat inscrutable and underdocumented.

Yep. The `-`/`_` mangling in PyPI only causes confusion. However, I believe it is OK to rename it in the `setup.py`.

**Comment by jakirkham** [comment]
> Yep. The `-`/`_` mangling in PyPI only causes confusion. However, I believe it is OK to rename it in the `setup.py`.

Raised upstream as issue ( https://github.com/dask/dask-labextension/issues/67 ).
