### ISSUE TITLE
Removing dask_labextension as duplicate

### ISSUE THREAD

**Issue by spencermathews** [conda-forge/dask_labextension-feedstock#6]
Perhaps as a consequence of Issue #1 there is an ancient [dask_labextension](https://anaconda.org/conda-forge/dask_labextension) still lingering on conda-forge. Should that not be deleted as duplicate?

**Comment by ocefpaf** [comment]
Unfortunately some people may be using those. We should identify them and ask them to use the one with the new name but I don't think we should remove the packages.

**Comment by spencermathews** [comment]
Only a single old version of the extension, 0.3.3, was published under the leftover duplicate package name. I don't presume it will ever get an update. And for that matter the same version exists under the current conda-forge package name (`dask-labextension`).

I think it's fair to say that anyone installing the package now should use the new package name, and it's not clear what impact removing the old one would have on users who have installed it already. If anything, it might offer them a clue to switch to the new name.

For the other 99.9% of users, unnecessarily having two almost identical looking packages on conda-forge is confusing. Just a thought.

**Comment by ocefpaf** [comment]
#9 adds both versions.
